import Head from "next/head";
import Layout from "../../components/Layout";
import Sidebar from "../../components/Sidebar";
import Image from "next/image";
import shoes from "../../images/shoes.jpg";
import styles from "../page.module.css";

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <Layout>
        <div className={styles.mastheadWrap}>
          <Image
            layout="fill"
            objectFit="cover"
            objectPosition="center"
            quality={100}
            src={shoes}
            alt="Picture of the author"
          />
          <div className={`${styles.heading} container`}>
            <h1>North Florida Chiropractic Physical Therapy</h1>
            <p>
              Dr. Jason Orlando | Serving Orange Park for over 20
              years
            </p>
          </div>
        </div>
        <main>
          <div className="container">
            <div className={styles.pageWrap}>
              <article>
                <h1>About Us</h1>
                <div>
                  <div>
                    <p>
                      North Florida Chiropractic Physical Therapy
                      (NFCPT) is a full service Orange Park
                      chiropractic center. Founded in 1999, we have
                      been providing premium chiropractic services in
                      the{" "}
                      <a
                        title="Town of Orange Park"
                        href="http://www.townoforangepark.com/"
                      >
                        Orange Park area
                      </a>{" "}
                      for over fifteen years.
                    </p>
                    <h2>Our Patients</h2>
                    <p>
                      Our patients come to us suffering from a wide
                      range of spine and structural issues. Some are
                      affected by pain related to lifestyle or
                      genetics. Others are recovering from sport or
                      work related injuries. Many of our patients are
                      car accident victims looking for diagnosis and
                      post-accident therapy. Whatever the cause of a
                      patient’s pain is, we will diagnose it on the
                      first visit. Once diagnosed we will begin a
                      customized treatment plan at our Orange Park
                      Chiropractic Center.
                    </p>
                    <h2>Our Philosophy</h2>
                    <p>
                      The NFCPT team has a philosophy of addressing
                      the causes of pain, not just the symptoms of it.
                      Our team of therapists focuses on the diagnosis
                      of a problem first and the treatment of it
                      second. A correct diagnosis is crucial to a
                      timely recovery and is a critical part of our
                      process. Upon diagnosis, if we feel the patient
                      is suffering from symptoms that are not
                      chiropractic, we will refer them to one of our
                      colleagues for further evaluation or treatment.
                      Other types of health care providers we refer to
                      are: neurosurgeons, orthopedists, psychiatrists,
                      family doctors, and nutritionists.
                    </p>
                    <h3>A Full Spectrum Approach</h3>
                    <p>
                      The NFCPT treatment plan is a full spectrum
                      approach. We focus on five main techniques:
                    </p>
                    <ul>
                      <li>gentle joint manipulation</li>
                      <li>joint mobilization</li>
                      <li>therapeutic massage</li>
                      <li>stabilization exercise</li>
                      <li>therapeutic stretching</li>
                    </ul>
                    <h4>Not Something We Came Up With Overnight…</h4>
                    <p>
                      This is not an approach we came up with
                      overnight. Over twenty years of hands on
                      treatment has refined this technique to where it
                      is today. We feel that this strategy provides
                      the best results for our patients, it has been
                      tried and tested, and it is what sets us apart
                      from other providers.
                    </p>
                    <h2>
                      Make An Appointment For A Free Consultation
                    </h2>
                    <p>
                      North Florida Chiropractic Physical Therapy is a
                      leading provider of Orange Park chiropractic
                      services. Call us today to schedule your free
                      consultation and begin your custom treatment
                      plan.
                    </p>

                    <p></p>
                  </div>
                </div>
              </article>
              <Sidebar />
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
}
