import Head from "next/head";
import Layout from "../../components/Layout";

export default function FirstVisit() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <Layout>First Visit</Layout>
    </>
  );
}
