import Head from "next/head";
import Link from "next/link";
import Hero from "../components/Hero";
import Intro from "../components/Intro";
import CallToAction from "../components/CallToAction";
import Treatments from "../components/Treatments";
import BottomBlocks from "../components/BottomBlocks";
import Mission from "../components/Mission";
import Layout from "../components/Layout";
import { gql } from "@apollo/client";
import { client } from "../lib/apollo";

export async function getStaticProps() {
  const result = await client.query({
    query: gql`
      query GetWPPages {
        pages {
          nodes {
            title
            uri
            content
            date
            slug
          }
        }
      }
    `,
  });
  console.log(result);

  return {
    props: {
      pages: result.data.pages.nodes,
    },
  };
}

export default function Home({ pages }) {
  return (
    <>
      <Head>
        <title>
          Orange Park Chiropractor | North Florida Chiropractic
          Physical Therapy
        </title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <Layout>
        <Hero />
        <Intro />
        <Mission />
        {/* <CallToAction /> */}
        <Treatments />
        <BottomBlocks />
        <ul>
          {pages.map(({ uri, slug, title, content }) => {
            return (
              <li key="uri">
                <Link href={uri}>
                  <a>{title}</a>
                </Link>
              </li>
            );
          })}
        </ul>
      </Layout>
    </>
  );
}
