import { useRef } from 'react';
import Head from 'next/head';
import Hero from "../components/Hero";
import CallToAction from "../components/CallToAction";
import Treatments from "../components/Treatments";
import SimpleSlider from "../components/SimpleSlider";
import Mission from "../components/Mission";
import useIntersecionObserver from "../hooks/useIntersectionObserver";
import Layout from "../components/Layout";

export default function Home({ title }) {
  const ref = useRef(null);
  const entry = useIntersecionObserver(ref, {})
  const isVisible = !!entry?.isIntersecting

  console.log(`Render Section ${title}`, { isVisible })


  return (
    <>
      <Head>
        <title>Orange Park Chiropractor | North Florida Chiropractic Physical Therapy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Hero />
        <CallToAction />
        <Mission />
        <Treatments />
        <SimpleSlider />
      </Layout>
    </>
  )
}
