import Head from 'next/head'
import Layout from "../components/Layout";

export default function MassageTherapy() {
  return (
    <>
      <Head>
        <title>MassageTherapy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        MassageTherapy
      </Layout>

    </>
  )
}
