import Head from 'next/head'
import Layout from "../components/Layout";

export default function PhysicalTherapy() {
  return (
    <>
      <Head>
        <title>PhysicalTherapy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        PhysicalTherapy
      </Layout>

    </>
  )
}
